# Generated by Django 5.0.4 on 2024-05-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="po_number",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
