# Generated by Django 5.0.3 on 2024-05-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_po_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="po_delivered_on",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the PO is sucessfully delivered",
                null=True,
            ),
        ),
    ]
