# Generated by Django 5.0.3 on 2024-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance_history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperformance",
            name="fulfillment_rate",
            field=models.FloatField(
                blank=True,
                help_text="Historical record of Percentage of purchase orders fulfilled without issues.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="on_time_delivery_rate",
            field=models.FloatField(
                blank=True,
                help_text="Historical record of the  Percentage of orders delivered by the promised date",
                null=True,
            ),
        ),
    ]
